name: Putty CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  putty:
    name: Putty Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        mode: [release, debug]
        exclude:
          - os: macos-latest
            compiler: clang
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Coverage
      run: pip3 install coverage
    
    - name: Install Autoconf to Mac OS
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake libtool

    - name: Use Release flags
      if: matrix.mode == 'release'
      run: echo "GITHUB_CFLAGS=-O2" >> $GITHUB_ENV

    - name: Use Debug 
      if: matrix.mode == 'debug'
      run: echo "GITHUB_CFLAGS=-O0 -fprofile-arcs -ftest-coverage -g" >> $GITHUB_ENV

    - name: Use Clang
      if: matrix.compiler == 'clang'
      run: echo "CC=clang" >> $GITHUB_ENV
  
    - name: Generate Makefiles
      run: ./mkfiles.pl
    
    - name: Reconfigure
      run: autoreconf -fi

    - name: Configure
      run: ./configure --prefix=${{ github.workspace }} CFLAGS="$GITHUB_CFLAGS"
    
    - name: Make
      run: make testcrypt cgtest testsc
    
    - name: Make Pageant
      if: matrix.os == 'ubuntu-latest'
      run: make pageant

    - name: Run Pageant
      if: matrix.os == 'ubuntu-latest'
      run: ./pageant --exec ./test/agenttest.py

    - name: Run CG test
      run: ./cgtest
    
    - name: Run Cryptsuite
      run: coverage.py run ./test/cryptsuite.py
    
    - name: Run SC
      run: ./testsc
  
    - name: Upload Coverage
      uses: codecov/codecov-action@v1.0.15
